spring.application.name=ecom-proj

spring.datasource.url=jdbc:postgresql://localhost:5432/ems
spring.datasource.username=postgres
spring.datasource.password=Mdsaif@123
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.show-sql=true

/* it tells the hibernate to create the tables automatically if not present in the database */
spring.jpa.hibernate.ddl-auto=update 

spring.h2.console.enabled=true

spring.jpa.defer-datasource-initialization = true





